POST http://3.111.170.113:8000/api/plantOwner/register
Content-Type: application/json

{
    "plantID" : "190",
    "userID": "1002",
    "plantTypeID": "P0005",
    "addedDate": "2022-12-18"
}

###
POST http://localhost:8000/api/plantOwner/register
Content-Type: application/json

{
    "plantID" : "20",
    "userID": "1002",
    "plantTypeID": "P0010",
    "addedDate": "2022-12-20"
}

###
GET http://3.111.170.113:8000/api/plantOwner/1002