//POST http://3.110.142.169:8000/user

POST http://3.111.170.113:8000/api/user/register
Content-Type: application/json

{
    "userName" : "chamudi j",
    "email": "chamudi222@gmail.com",
    "mobileNo": "0786566",
    "userPassword": "sdado",
    "joinDate": "2022-11-18"
}

###
POST http://localhost:8000/api/user/register
Content-Type: application/json

{
    "userName" : "Anushanga Pavith",
    "email": "chamudi13@gmail.com",
    "mobileNo": "07856000006566",
    "userPassword": "sdsdado",
    "joinDate": "2022-11-18"
}

###
POST http://localhost:8000/api/user/register
Content-Type: application/json

{
    "userName" : "",
    "email": "",
    "mobileNo": "",
    "userPassword": "",
    "joinDate": ""
}

###
GET  http://localhost:8000/api/user/getUser
Content-Type: application/json

{
    "email" : "chamara@gmail.com"
}

###
GET  http://3.111.170.113:8000/api/user/getUser
Content-Type: application/json

{
    "email" : "chamara@gmail.com"
}